Add processor parse container log native
quzard/ilogtail pull request #4
Opened 2024-02-21 09:57 UTC by quzard

2024-02-21 11:47 UTC, henryzhx8 requested changes

2024-02-21 11:47 UTC, henryzhx8 commented on core/models/PipelineEventGroup.h
> +    FILE_ENCODING,
这是啥？

2024-02-21 11:47 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +    }
特别注意有没有迭代器失效问题

2024-02-21 11:47 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +bool ProcessorParseContainerLogNative::ProcessEvent(const StringView& containerType, PipelineEventPtr& e) {
所有的stringview都直接按值传递

2024-02-21 11:47 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +    if (!doc.HasMember(DOCKER_JSON_LOG.c_str()) || !doc.HasMember(DOCKER_JSON_TIME.c_str())
不要先hasmember，再getmember，直接findmember，然后用迭代器，效率会高很多

2024-02-21 11:47 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +}
这个有点hack了，虽然看起来是对的，但感觉风险很大，越界检查什么都没有。既然这样子弄了，那为啥不更直接点，在原始日志上硬解，还能更省内存。

2024-02-21 11:47 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.h
> +    std::string containerLogKey = "content"; // 容器日志字段
这个插件是一个完全新的插件还是替代go插件？如果是新的话，这些key的名字可以重新斟酌一下，包括time这个字段是不是直接不要了，默认作为__time__

2024-02-21 11:47 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +void ProcessorParseContainerLogNative::AddLog(const StringView& key,
这个包一层的意义？

2024-02-21 11:47 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +bool ProcessorParseContainerLogNative::DockerJsonLogLineParser(LogEvent& sourceEvent, PipelineEventPtr& e) {
这个e干啥用了？

2024-02-21 11:47 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +    StringView buffer = sourceEvent.GetContent(mSourceKey);
源字段删除考虑了吗？虽然恰好前后都是content，但不要将这种条件隐式表达。

2024-02-21 11:47 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +    if (contentValue.empty() || contentValue.length() < 5)
小于5是什么意思？

2024-02-21 11:47 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +        = std::search(contentValue.begin(), contentValue.end(), CONTIANERD_DELIMITER.begin(), CONTIANERD_DELIMITER.end());
这个函数的效率怎么样？和find比

2024-02-21 11:47 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +    if (sourceValue != "stdout" && sourceValue != "stderr")
docker那为什么没有这个？

2024-02-21 11:47 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +        StringBuffer containerLogKeyBuffer = sourceEvent.GetSourceBuffer()->CopyString(containerLogKey);
这几个一样的可以一个logGroup共享一个吗？

2024-02-21 11:47 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +    if (pch1 >= contentValue.end() - 1) {
这里的条件为什么和下面两个不一样？

2024-02-21 11:47 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +    }
这一堆适当合并下吧，太啰嗦了

2024-02-21 11:47 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
这里有没有考虑常规格式之外突然出现一下异常信息的情况？

2024-02-23 01:56 UTC, quzard commented on core/models/PipelineEventGroup.h
> +    FILE_ENCODING,
用于Meta data

2024-02-23 02:25 UTC, quzard commented on core/processor/ProcessorParseContainerLogNative.cpp
> +}
在原始日志上硬解也要分配临时空间存储json解析后的content。自己要实现一个content的json解析函数

2024-02-23 02:31 UTC, quzard commented on core/processor/ProcessorParseContainerLogNative.cpp
> +    StringView buffer = sourceEvent.GetContent(mSourceKey);
如果源字段被删除了，GetContent会返回一个空的StringView。下面有判断空的逻辑

2024-02-23 02:39 UTC, quzard commented on core/processor/ProcessorParseContainerLogNative.cpp
docker_json-file靠是否json解析成功来判断。containerd_text 有判断日志格式是否合法。不合法就直接返回原始日志

2024-02-25 09:38 UTC, henryzhx8 requested changes

2024-02-25 09:38 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
>          return true;
这个判断条件省了吧，其它解析插件也没单独拎出来

2024-02-25 09:38 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +    if (pch1 >= contentValue.end()) {
```suggestion
    if (pch1 == contentValue.end()) {
```

2024-02-25 09:38 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
>      }
这里有明显的逻辑漏洞，以下几种情况都会有问题：
1. 时间 stdout F（消息就是F）
2. 时间 stdout Fa msg（消息是Fa msg）

正确的逻辑分解方法：
1. 首先从pch2+1开始找第三个分隔符，如果找不到，说明pch2+1到结束的都是content（消息就是F这种）
2. 如果找到第三个分隔符pch3，则判断pch3-pch2是否等于2且pch2+1是否是F或者P，如果符合，说明pch3+1到结束是content（常规）
4. 否则，pch2+1到结束都是content（消息就是Fa msg这种）

2024-02-25 09:38 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
>          return true;
像这种地方，其实都是异常情况，需要打warning日志的，所以函数签名里还要加一个errorMsg的出参，到外层的ProcessEvent函数里去打印具体的日志。

2024-02-25 09:38 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +                                                            StringView partTag,
这个参数直接用bool isPartialLog

2024-02-25 09:38 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.h
> +    std::string containerLogKey = "content"; // 容器日志字段
这个也改成static const

2024-02-25 09:38 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.h
> +    static const std::string DOCKER_JSON_STREAM_TYPE; // docker json 流字段
这些其它类会用吗？不会的话放private

2024-02-25 09:38 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.h
> +};
这个不需要了，containerTimeKey这几个参数变成类常量以后，setcontent的时候可以直接stringview引用，不需要再CopyString了，因为相当于全局变量，生命周期肯定比loggroup长

2024-02-25 09:38 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.h
> +    void AddDockerJsonLog(char** data, const StringBuffer key, const StringView value, LogEvent& targetEvent);
1. StringView不需要const修饰
2. char**不太常用，还是改成两个参数吧，加一个index记录当前位置

根据之前的描述，可以直接改成
```suggestion
    void AddDockerJsonLog(char* data, size_t &index, StringView key, StringView value, LogEvent& targetEvent);
```

2024-02-25 09:38 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +        return true;
```suggestion
```

2024-02-25 09:38 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +    }
和containerdParse一样，解析类错误通过errorMsg传递出去，在ProcessEvent里统一处理

2024-02-25 09:38 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +    }
同上，类似的错误处理统一由外部处理

2024-02-25 09:38 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +    };
这个放到JsonUtil里吧

2024-02-25 09:38 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +        return it != doc.MemberEnd() ? StringView(it->value.GetString()) : StringView();
```suggestion
        return it != doc.MemberEnd() ? StringView(it->value.GetCString()) : StringView();
```
可以省一次string构造

2024-02-25 09:38 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.cpp
> +        data = const_cast<char*>(stringBuffer.data);
这个也应该属于非预期情况，需要warning，且直接返回，不要再继续了

2024-02-25 09:38 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.h
> +                                 ContainerStdoutKeyStringBuffer* containerStdoutKeyStringBuffer);
综合之前的所有描述，函数签名改成如下：
```suggestion
    void AddContainerdTextLog(StringView time, StringView source, StringView content, bool isPartialLog, LogEvent& sourceEvent);
    bool ParseContainerdLogLine(LogEvent& sourceEvent, std::string& errorMsg);
    bool ParseDockerJsonLogLine(LogEvent& sourceEvent, std::string& errorMsg);
```

2024-02-25 09:38 UTC, henryzhx8 commented on core/processor/ProcessorParseContainerLogNative.h
> +                      ContainerStdoutKeyStringBuffer* containerStdoutKeyStringBuffer);
```suggestion
    bool ProcessEvent(StringView containerType, PipelineEventPtr& e);
```

2024-02-26 09:18 UTC, quzard commented on core/processor/ProcessorParseContainerLogNative.h
> +    static const std::string DOCKER_JSON_STREAM_TYPE; // docker json 流字段
回退逻辑里需要

2024-04-02 12:00 UTC, closed without merging